src/project/urls.py
from django.urls import path
from .views import (
    ProjectDetailView,
    ProjectListView,
)

app_name = 'project'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project-list'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
]

src/project_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
)

urlpatterns = [
    path('', RedirectView.as_view(url='user/dashboard')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('project/', include('project.urls', namespace='project')),
    path('user/', include('user.urls', namespace='user')),
]

src/user/urls.py
from django.urls import path
from .views import (
    DashboardView,
    UserListView,
    UserCreateView,
    UserDetailView,
    UserDeleteView,
    UserUpdateView,
)

app_name = 'user'

urlpatterns = [
    path('dashboard', DashboardView.as_view(), name='user-dashboard'),
    path('list/', UserListView.as_view(), name='user-list'),
    path('create/', UserCreateView.as_view(), name='user-create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
]

src/project/models.py
from django.db import models
from django.db.models.deletion import SET_NULL


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Task(models.Model):
    STATUS = [
        ('Assigned', 'Assigned'),
        ('In Process', 'In Process'),
        ('Complete', 'Complete'),
    ]

    name = models.CharField(max_length=100)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, max_length=20)

    def __str__(self):
        return self.name

src/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    USER_ROLE = (
        ('Admin', 'Admin'),
        ('HR', 'HR'),
        ('PM', 'PM'),
        ('Developer', 'Developer'),
    )
    
    role = models.CharField(choices=USER_ROLE, max_length=50)

src/user/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField

from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'role'
        )
        field_classes = {'username': UsernameField}

src/project/views.py
from django.shortcuts import render
from django.urls.base import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Project, Task


class ProjectListView(LoginRequiredMixin, generic.ListView):
    template_name = 'project/project_list.html'
    context_object_name = 'projects'

    def get_queryset(self):
        return Project.objects.all()


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'project/project_detail.html'
    context_object_name = 'project'

    def get_queryset(self):
        return Project.objects.all()

src/user/views.py
from django.shortcuts import render
from django.urls.base import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User
from .forms import CustomUserCreationForm


class DashboardView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'user/dashboard.html'


class UserListView(LoginRequiredMixin, generic.ListView):
    template_name = 'user/user_list.html'
    context_object_name = 'users'

    def get_queryset(self):
        return User.objects.all()


class UserCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'user/user_create.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse('user:user-list')


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'user/user_detail.html'
    context_object_name = 'user'

    def get_queryset(self):
        return User.objects.all()


class UserDeleteView(LoginRequiredMixin, generic.DeleteView):

    def get_queryset(self):
        return User.objects.all()

    def get_success_url(self):
        return reverse('user:user-list')


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'user/user_update.html'
    form_class = CustomUserCreationForm

    def get_queryset(self):
        return User.objects.all()

    def get_success_url(self):
        return reverse('user:user-detail', kwargs={'pk': self.get_object().id})

src/project/templates/project/project_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ project.name }}</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">{{ project.description }}</p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <p>Task</p>
            <table class="mt-5 table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th id="task-name"
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                            Name</th>
                        <th id="task-status"
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Status</th>
                        <th id="task-action"
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in project.task_set.all %}
                    <tr>
                        <td class="border-t-2 border-gray-200 px-4 py-3">{{ task.name }}</td>
                        <td class="border-t-2 border-gray-200 px-4 py-3">{{ task.status }}</td>
                        <td class="border-t-2 border-gray-200 px-4 py-3 text-blue-500 hover:text-blue-600"><a
                                href="#">Edit</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock content %}

src/project/templates/project/project_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h2 class="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">ROOF PARTY POLAROID</h2>
            <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">Project List</h1>
        </div>
        <div class="flex flex-wrap -m-4">
            {% for project in projects %}

            <div class="p-4 md:w-1/3">
                <div class="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                    <div class="flex items-center mb-3">
                        <div
                            class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 text-white flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <h2 class="text-gray-900 text-lg title-font font-medium">{{ project.name }}</h2>
                    </div>
                    <div class="flex-grow">
                        <p class="leading-relaxed text-base">{{ project.description }}</p>
                        <a href="{% url 'project:project-detail' project.id %}"
                            class="mt-3 text-indigo-500 inline-flex items-center">Details
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Manager</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

src/templates/navbar.html
<header class="text-gray-600 body-font bg-gray-100">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round"
                stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
                viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">Tailblocks</span>
        </a>

        {% if request.user.is_authenticated %}

        <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
            {% if request.user.role == 'Admin' or request.user.role == 'HR' %}
            <a href="{% url 'user:user-list' %}" class="mr-5 hover:text-gray-900">Users</a>
            {% endif %}
            <a href="{% url 'project:project-list' %}" class="mr-5 hover:text-gray-900">Project</a>
            <a class="mr-5 hover:text-gray-900">Third Link</a>
            <a class="mr-5 hover:text-gray-900">Fourth Link</a>
        </nav>

        Logged in as: {{ request.user.username }}
        <a href="{% url 'logout' %}"
            class="ml-5 inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Logout
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>

        {% endif %}

    </div>
</header>

src/user/templates/user/dashboard.html
{% extends "base.html" %}

src/user/templates/user/user_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero"
            src="https://dummyimage.com/720x600">
        <div class="text-center lg:w-2/3 w-full">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                {{ user.first_name }} {{ user.last_name }} ({{ user.username }})
            </h1>
            <h3>{{ user.role }}</h3>
            <p class="mb-8 leading-relaxed">Are you sure want to delete this user?</p>
            <div class="flex justify-center">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <a href="{% url 'user:user-detail' user.id %}"
                        class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">
                        Cancel
                    </a>
                    <button type="submit"
                        class="ml-4 inline-flex text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-700 rounded text-lg">
                        Delete
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

src/user/templates/user/user_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
        <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
            <h1 class="title-font font-medium text-3xl text-gray-900">Slow-carb next level shoindcgoitch ethical
                authentic, poko scenester</h1>
            <p class="leading-relaxed mt-4">Poke slow-carb mixtape knausgaard, typewriter street art gentrify hammock
                starladder roathse. Craies vegan tousled etsy austin.</p>
        </div>
        <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
            <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Create new user</h2>
            <form method="POST" class="relative mb-4"">
                {% csrf_token %}
                {{ form|crispy }}
            <button
                type=" submit"
                class="mt-5 w-full text-white bg-yellow-500 border-0 py-2 px-8 focus:outline-none hover:bg-yellow-600 rounded text-lg">
                Login</button>
            </form>
            <p class="text-xs text-gray-500 mt-3">Literally you probably haven't heard of them jean shorts.</p>
        </div>
    </div>
</section>

{% endblock content %}

src/user/templates/user/user_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
            <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">{{ user.role }}</h2>
                <h1 class="text-gray-900 text-2xl title-font font-medium mb-1">
                    {{ user.first_name }} {{ user.last_name }} ({{ user.username }})</h1>
                <div class="flex mb-4">
                    <span class="flex items-center">
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                            <path
                                d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z">
                            </path>
                        </svg>
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                            <path
                                d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z">
                            </path>
                        </svg>
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                            <path
                                d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z">
                            </path>
                        </svg>
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                            <path
                                d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z">
                            </path>
                        </svg>
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                            <path
                                d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z">
                            </path>
                        </svg>
                        <span class="text-gray-600 ml-3">4 Reviews</span>
                    </span>
                    <span class="flex ml-3 pl-3 py-2 border-l-2 border-gray-200 space-x-2s">
                        <a class="text-gray-500">
                            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                class="w-5 h-5" viewBox="0 0 24 24">
                                <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                            </svg>
                        </a>
                        <a class="text-gray-500">
                            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                class="w-5 h-5" viewBox="0 0 24 24">
                                <path
                                    d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z">
                                </path>
                            </svg>
                        </a>
                        <a class="text-gray-500">
                            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                class="w-5 h-5" viewBox="0 0 24 24">
                                <path
                                    d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z">
                                </path>
                            </svg>
                        </a>
                    </span>
                </div>
                <p class="leading-relaxed">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha
                    taximy chia microdosing tilde DIY. XOXO fam indxgo juiceramps cornhole raw denim forage brooklyn.
                    Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra
                    jean shorts keytar banjo tattooed umami cardigan.</p>
                <div class="flex items-center pb-5 border-b-2 border-gray-100 mb-5">
                </div>
                <div class="flex">
                    {% if request.user.role == 'Admin' %}

                    <a href="{% url 'user:user-update' user.id %}"
                        class="flex text-white bg-yellow-500 border-0 py-2 px-10 focus:outline-none hover:bg-yellow-600 rounded">
                        Edit
                    </a>
                    <a href="{% url 'user:user-delete' user.id %}"
                        class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">
                        Delete
                    </a>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

src/user/templates/user/user_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-6 mx-auto">
        {% if request.user.role == 'Admin' %}

        <a class="hover:text-blue-700" href="{% url 'user:user-create' %}">
            Create new user
        </a>

        {% endif %}
        <div class="flex flex-wrap -m-2 mt-4">
            {% for user in users %}

            <div class="p-2 lg:w-1/3 md:w-1/2 w-full">
                <a href="{% url 'user:user-detail' user.id %}">
                    <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
                        <img alt="team"
                            class="w-16 h-16 bg-gray-100 object-cover object-center flex-shrink-0 rounded-full mr-4"
                            src="https://dummyimage.com/80x80">
                        <div class="flex-grow">
                            <h2 class="text-gray-900 title-font font-medium">
                                {{ user.first_name }} {{ user.last_name }} ({{ user.username }})
                            </h2>
                            <p class="text-gray-500"></p>
                            <p class="text-gray-500">{{ user.role }}</p>
                        </div>
                    </div>
                </a>
            </div>

            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

src/user/templates/user/user_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
        <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
            <h1 class="title-font font-medium text-3xl text-gray-900">Slow-carb next level shoindcgoitch ethical
                authentic, poko scenester</h1>
            <p class="leading-relaxed mt-4">Poke slow-carb mixtape knausgaard, typewriter street art gentrify hammock
                starladder roathse. Craies vegan tousled etsy austin.</p>
        </div>
        <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
            <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Update user</h2>
            <form method="POST" class="relative mb-4"">
                {% csrf_token %}
                {{ form|crispy }}
                <button type=" submit"
                class="mt-5 w-full text-white bg-yellow-500 border-0 py-2 px-8 focus:outline-none hover:bg-yellow-600 rounded text-lg">
                Update
                </button>
                <a href="{% url 'user:user-detail' user.id %}"
                    class="mt-5 w-full text-white bg-blue-500 border-0 py-2 px-8 focus:outline-none hover:bg-blue-600 rounded text-lg">
                    Cancel
                </a>
            </form>
            <p class="text-xs text-gray-500 mt-3">Literally you probably haven't heard of them jean shorts.</p>
        </div>
    </div>
</section>

{% endblock content %}